language:
  php

php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer install
  - wget https://github.com/infection/infection/releases/download/0.7.1/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.7.1/infection.phar.pubkey
  - chmod +x infection.phar

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --testdox
  - ./infection.phar --min-msi=95 --min-covered-msi=100

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false
